### PR TITLE
updated ReadMe and go.mod to reflect the new Issue - #13

### PR DESCRIPTION
**Pull request by Nava890**
Updated the ReadMe and go.mod to reflect the new url for this issue #13 

Tested with the forked repository 
image

### CODE REVIEW

**Review by ANIRUDH-333 — APPROVED** [review]

**Review by mailprak — APPROVED** [review]

**Comment by mailprak** [comment]
@Nava890 Have merged the PR. 
Could not find option enabled to Manage the access for write access in the settings.

**Comment by anoop2811** [comment]
@Nava890 : Thank you for your contribution!

**Comment by Nava890** [comment]
I will contribute more actively in the future, focusing not only on documentation but also on code contributions.

**Comment by anoop2811** [comment]
@Nava890 : Thank you! Do you use fern in any capacity? We are planning to add an adopters file later, but would be great to earn about your use cases.

**Comment by Nava890** [comment]
Hi @anoop2811, no not really, I am in the process of learning go and ginkgo for testing.

**Pull request merged**
